version: '2'
services:
  gateway-app:
    image: gateway
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATA_MONGODB_URI=mongodb://gateway-mongodb:27080
      - SPRING_DATA_MONGODB_DATABASE=gateway
      - JHIPSTER_CACHE_REDIS_SERVER=redis://gateway-redis:6380
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://elasticsearch:9200
      - KAFKA_BOOTSTRAPSERVERS=kafka:9092
    ports:
      - 8080:8080
  gateway-mongodb:
    extends:
      file: mongodb.yml
      service: gateway-mongodb
  gateway-redis:
    extends:
      file: redis.yml
      service: gateway-redis
  elasticsearch:
    extends:
      file: elasticsearch.yml
      service: elasticsearch
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
